repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
    - id: flake8
      args:
      - --max-line-length=150
      - --max-complexity=60
      - --ignore=E203,W503,E501
- repo: https://github.com/psf/black
  rev: 25.1.0
  hooks:
    - id: black
      args:
      - --line-length=150

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: check-merge-conflict
